/** Applies pending SQL migrations (generated by drizzle-kit) to the current DB. */
import { migrate } from 'drizzle-orm/pglite/migrator';
import { getDb } from './client';
import { childLogger } from '../logger';

const log = childLogger('migrate');

/** Idempotently brings the database schema up to date. Safe to call on every boot. */
export async function runMigrations(): Promise<void> {
  const { db } = await getDb();
  await migrate(db, { migrationsFolder: './drizzle' });
  log.info('migrations applied');
}
